/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package onoh;

import java.sql.SQLException;
import javax.swing.JOptionPane;
/**
 *
 * @author rishu
 */
public class ONOH_Login extends javax.swing.JFrame {

    /**
     * Creates new form ONOH_Login
     */
    int f;
    DBC db;
    public ONOH_Login(int t) {
        super("LOGIN");
        initComponents();
        f = t;
        db = new DBC();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfid = new javax.swing.JTextField();
        btnlogin = new javax.swing.JButton();
        tfpass = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LOGIN");

        jLabel1.setText("ID:");

        jLabel2.setText("Password:");

        btnlogin.setText("LOGIN");
        btnlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnloginActionPerformed(evt);
            }
        });

        tfpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfpassActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfid, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)
                            .addComponent(tfpass)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(203, 203, 203)
                        .addComponent(btnlogin, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(103, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfid, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(tfpass, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(62, 62, 62)
                .addComponent(btnlogin, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnloginActionPerformed
        String pass = new String(tfpass.getPassword());
        String qry = "";
        if (f == 1)
        {
            //System.out.println(tfpass.getPassword());
            qry = "SELECT Password FROM onohuser WHERE UID = '"+tfid.getText()+"'";
            try
            {
                db.rs1 = db.stm.executeQuery(qry);
                if (db.rs1.next())
                {
                    if (pass.equals(db.rs1.getString(1)))
                    {
                        new LoginData(tfid.getText());
                        new ONOH_UDashboard().setVisible(true);
                        this.setVisible(false);
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(null, "Incorrect Password!!!", "Try Again", JOptionPane.ERROR_MESSAGE);
                        tfpass.setText("");
                    }
                }
                else
                {
                    JOptionPane.showMessageDialog(null, "ID Not registerd!!!", "", JOptionPane.ERROR_MESSAGE);
                    tfid.setText("");
                    tfpass.setText("");
                }
            }
            catch (SQLException e)
            {
                e.printStackTrace();
            }
        }
        if (f == 2)
        {
            qry = "SELECT Password FROM onoh_hospital WHERE UID = '"+tfid.getText()+"'";
            try
            {
                db.rs1 = db.stm.executeQuery(qry);
                if (db.rs1.next())
                {
                    if (pass.equals(db.rs1.getString(1)))
                    {
                        new LoginData(tfid.getText());
                        new ONOH_HDashboard().setVisible(true);
                        this.setVisible(false);
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(null, "Incorrect Password!!!", "Try Again", JOptionPane.ERROR_MESSAGE);
                        tfpass.setText("");
                    }
                }
                else
                {
                    JOptionPane.showMessageDialog(null, "ID Not registerd!!!", "", JOptionPane.ERROR_MESSAGE);
                    tfid.setText("");
                    tfpass.setText("");
                }
            }
            catch (SQLException e)
            {
                e.printStackTrace();
            }
            
        }
       if (f == 3)
       {
           qry = "SELECT Password FROM onohstore WHERE UID = '"+tfid.getText()+"'";
            try
            {
                db.rs1 = db.stm.executeQuery(qry);
                if (db.rs1.next())
                {
                    if (pass.equals(db.rs1.getString(1)))
                    {
                        new LoginData(tfid.getText());
                        new ONOH_SDashboard().setVisible(true);
                        this.setVisible(false);
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(null, "Incorrect Password!!!", "Try Again", JOptionPane.ERROR_MESSAGE);
                        tfpass.setText("");
                    }
                }
                else
                {
                    JOptionPane.showMessageDialog(null, "ID Not registerd!!!", "", JOptionPane.ERROR_MESSAGE);
                    tfid.setText("");
                    tfpass.setText("");
                }
            }
            catch (SQLException e)
            {
                e.printStackTrace();
            }
       }
        
        
        
        
       
    }//GEN-LAST:event_btnloginActionPerformed

    private void tfpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfpassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfpassActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ONOH_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ONOH_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ONOH_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ONOH_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               ONOH_Login ob =  new ONOH_Login(1);
               ob.setLocationRelativeTo(null);
               ob.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnlogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField tfid;
    private javax.swing.JPasswordField tfpass;
    // End of variables declaration//GEN-END:variables
}
